import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/component/Header";
import TouchFlash from "./component/ScroolFlashIcon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {






  return (
    <html lang="en">

      <body
          style={{direction:"rtl",backgroundColor:"#F9FAFF"}}

        className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden antialiased`}
      >
<Header/>
        <TouchFlash />
        {children}
      </body>
    </html>
  );
}
