import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/component/Header";
import TouchFlash from "./component/ScroolFlashIcon";
import SmoothScroll from "@/app/component/SmoothScroll";
import ScrollButton from "./component/ScreoolBotton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {






  return (
    <html lang="en">

      <body
          style={{backgroundColor:"#292929",overflowInline:"hidden"}}

        className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden-hidden  overflow-x-hidden antialiased`}
      >
      <SmoothScroll>
         <ScrollButton />
{/* <Header/> */}
        {/* <TouchFlash /> */}
        {children}    </SmoothScroll>
      </body>

    </html>
  );
}
